Struct.new('MyStruct',
           :cat,
           :etur,
           :est,
           :iam,
           :ent,
           :et,
           :aabor,
           :quaa,
           :quipa,
           :estat,
           :deseqama,
           :dolor,
           :occat,
           :enim,
           :sing,
           :ea,
           :sicingaeaada,
           :labam,
           :eaaua,
           :suaa,
           :amea,
           :magat,
           :lam,
           :re,
           :ex,
           )
def expected
  Struct::MyStruct.new(
    'Venia con maga qaboadaa.',
    'Esea alit ut ofabo.',
    'Etuata ing mina famcom.',
    'Irur ciat nullum nis.',
    'Sin maga eaaec aate.',
    'Idua amag la ip.',
    'Dolo cida maal exceaad.',
    'Exce exea autat alabaa.',
    'Oat adaa eser qatat.',
    'Paar seaali ocaabor prabo.',
    'Cona catat exat dolo.',
    'Miat dat adid labo.',
    'Coam ea naat caatati.',
    'Idaat cat do in.',
    'Ut quatat adaat excae.',
    'Adip iatatet auaa vea.',
    'In ex con ent.',
    'Oatiat in amcons adaature.',
    'Exatate labo ulla re.',
    'Auta te esta para.',
    'Ipia sea commol magna.',
    'Endenia eur in aliamaga.',
    'Noabor modo autaa aata.',
    'Ad irab ut cupar.',
    'Si voaabor alit occaaa.',
    )
end

def actual
  Struct::MyStruct.new(
    'venia con maga qaboadaa.',
    'esea alit ut ofabo.',
    'etuata ing mina famcom.',
    'irur ciat nullum nis.',
    'Sin maga eaaec aate.',
    'Idua amag la ip.',
    'Dolo cida maal exceaad.',
    'Exce exea autat alabaa.',
    'oat adaa eser qatat.',
    'paar seaali ocaabor prabo.',
    'cona catat exat dolo.',
    'miat dat adid labo.',
    'Coam ea naat caatati.',
    'Idaat cat do in.',
    'Ut quatat adaat excae.',
    'Adip iatatet auaa vea.',
    'in ex con ent.',
    'oatiat in amcons adaature.',
    'exatate labo ulla re.',
    'auta te esta para.',
    'Ipia sea commol magna.',
    'Endenia eur in aliamaga.',
    'Noabor modo autaa aata.',
    'Ad irab ut cupar.',
    )
end