def expected
  {
      :ina => 'Alita tea loat qani.',
      :con => 'Et sia adid qua.',
      :dolupi => 'Parali coal alit qad.',
      :enaam => 'La ofadi aliq caat.',
      :qat => 'Magna voaa aaliqu maan.',
      :vent => 'Do velaa volor na.',
      :suata => 'Fadi iame adati na.',
      :ip => 'Utat iram adip voan.',
      :ex => 'Vat eiua exca inci.',
      :labor => 'Aut tatat proam iat.',
      :occaag => 'Co nulab nost paat.',
      :alitaaa => 'Eaam fugatia exat quis.',
      :cidaa => 'Enia adiaamea deseaat eliqui.',
      :eaalabalab => 'Aut te magna aliq.',
      :ut => 'Param ad dua idatu.',
      :ullaboa => 'Irat cona doat dunt.',
      :ip => 'Irur na nuaata doaga.',
      :duat => 'Noaga idat sara ex.',
      :anis => 'Sint adipi et aut.',
  }
end
def actual
  {
      :ina => 'Alita tea loat qani.',
      :con => 'Et sia adid qua.',
      :euaaag => 'Enta adaad idess utetu.',
      :enaam => 'la ofadi aliq caat.',
      :qat => 'Magna voaa aaliqu maan.',
      :vent => 'do velaa volor na.',
      :eaarisau => 'Taabore magn naatat in.',
      :ip => 'Utat iram adip voan.',
      :ex => 'Vat eiua exca inci.',
      :labor => 'aut tatat proam iat.',
      :esedat => 'Dola labor eu null.',
      :alitaaa => 'Eaam fugatia exat quis.',
      :cidaa => 'enia adiaamea deseaat eliqui.',
      :eaalabalab => 'Aut te magna aliq.',
      :cat => 'Cullum pa quip magat.',
      :ullaboa => 'Irat cona doat dunt.',
      :ip => 'Irur na nuaata doaga.',
      :duat => 'Noaga idat sara ex.',
      :eua => 'Quat comm laal inaa.',
  }
end
